name: ServerTweaks
version: ${project.version}
main: pl.psalkowski.servertweaks.ServerTweaksPlugin
api-version: '1.21'
description: Modular server utilities and tweaks for Paper servers
authors:
  - psalkowski
